# Generated by Django 5.1 on 2024-08-13 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortaleCorrispettivi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testo', models.TextField()),
                ('mese_misura', models.DateField()),
                ('stato', models.CharField(choices=[('empty', 'Nessuno'), ('ok', 'Risolto'), ('standby', 'In lavorazione'), ('alarm', 'Problema')], default='', max_length=50)),
                ('impianto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PortaleCorrispettivi.impianto')),
            ],
        ),
    ]
