# Generated by Django 5.0.7 on 2025-05-09 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortaleCorrispettivi', '0010_datimensilitabella'),
    ]

    operations = [
        migrations.AddField(
            model_name='datimensilitabella',
            name='origine_dati',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PortaleCorrispettivi.diarioletture'),
        ),
        migrations.AlterField(
            model_name='datimensilitabella',
            name='anno',
            field=models.IntegerField(editable=False),
        ),
    ]
