# Generated by Django 5.0.7 on 2025-05-15 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortaleCorrispettivi', '0017_punmonthlydata'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflow',
            name='anno',
            field=models.IntegerField(default=2025, verbose_name='Anno di riferimento'),
        ),
        migrations.AddField(
            model_name='cashflow',
            name='tipo_file',
            field=models.CharField(choices=[('FATTURAZIONE_TFO', 'Fatturazione TFO'), ('FATTURAZIONE_ALTRO', 'Fatturazione non incentivata'), ('INCASSI', 'Riepilogo pagamenti')], default='FATTURAZIONE_TFO', max_length=50, verbose_name='Tipo di file'),
        ),
    ]
