# Generated by Django 5.0.7 on 2025-09-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PortaleCorrispettivi", "0020_datienergianonincentivata_datitfo"),
    ]

    operations = [
        migrations.AddField(
            model_name="datienergianonincentivata",
            name="periodocompetenza",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="datitfo",
            name="periodocompetenza",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
