# Generated by Django 5.0.7 on 2024-07-31 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonitoraggioImpianti', '0002_impianto_potenza_business_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impianto',
            name='potenza_business_plan',
            field=models.FloatField(blank=True, default=0, help_text='Potenza da Business Plan', null=True, verbose_name='Potenza Business Plan'),
        ),
    ]
