# Generated by Django 5.0.7 on 2025-04-04 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutomazioneDati', '0003_remove_contatore_nome_impianto_contatore_impianto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='letturacontatore',
            name='autocons_campo',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='letturacontatore',
            name='autocons_ed',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='letturacontatore',
            name='autocons_gse',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
