# Generated by Django 5.0.7 on 2025-04-04 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AutomazioneDati', '0004_letturacontatore_autocons_campo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letturacontatore',
            name='autocons_campo',
        ),
        migrations.RemoveField(
            model_name='letturacontatore',
            name='autocons_ed',
        ),
        migrations.RemoveField(
            model_name='letturacontatore',
            name='autocons_gse',
        ),
    ]
