# Generated by Django 5.0.7 on 2025-04-10 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutomazioneDati', '0008_alter_letturacontatore_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='letturacontatore',
            name='autocons_campo',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Autoconsumo Campo'),
        ),
    ]
