# Generated by Django 5.0.7 on 2025-04-15 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutomazioneDati', '0013_remove_contatore_impianto_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='contatore',
            name='impianto_nickname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
