# Generated by Django 5.0.7 on 2025-04-15 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutomazioneDati', '0017_letturacontatore_prel_campo_letturacontatore_prel_ed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letturacontatore',
            name='prel_campo',
        ),
        migrations.RemoveField(
            model_name='letturacontatore',
            name='prel_ed',
        ),
        migrations.RemoveField(
            model_name='letturacontatore',
            name='prel_gse',
        ),
        migrations.RemoveField(
            model_name='letturacontatore',
            name='prod_campo',
        ),
        migrations.RemoveField(
            model_name='letturacontatore',
            name='prod_ed',
        ),
        migrations.RemoveField(
            model_name='letturacontatore',
            name='prod_gse',
        ),
        migrations.AlterField(
            model_name='letturacontatore',
            name='imm_campo_calcolato',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='Immissione Calcolata (totale_180n * k)'),
        ),
    ]
