# Generated by Django 5.0.7 on 2025-04-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutomazioneDati', '0021_remove_letturacontatore_data_presa'),
    ]

    operations = [
        migrations.AddField(
            model_name='letturacontatore',
            name='ora_lettura',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
