# Generated by Django 5.0.7 on 2025-04-23 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutomazioneDati', '0026_letturacontatore_data_presa'),
        ('MonitoraggioImpianti', '0005_linkportale_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contatore',
            name='impianto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contatori', to='MonitoraggioImpianti.impianto'),
        ),
        migrations.DeleteModel(
            name='Impianto',
        ),
    ]
