# Generated by Django 5.0.7 on 2025-04-24 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutomazioneDati', '0029_remove_letturacontatore_autocons_campo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='regsegnanti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anno', models.IntegerField()),
                ('mese', models.IntegerField()),
                ('prod_campo', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('prod_ed', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('prod_gse', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('prel_campo', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('prel_ed', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('prel_gse', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('autocons_campo', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('autocons_ed', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('autocons_gse', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('imm_campo', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('imm_ed', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('imm_gse', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('contatore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reg_segnanti', to='AutomazioneDati.contatore')),
            ],
            options={
                'verbose_name': 'Registro Segnante',
                'verbose_name_plural': 'Registri Segnanti',
                'unique_together': {('contatore', 'anno', 'mese')},
            },
        ),
    ]
