# Generated by Django 5.0.7 on 2025-04-30 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutomazioneDati', '0030_regsegnanti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regsegnanti',
            name='contatore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diarioenergie', to='AutomazioneDati.contatore'),
        ),
    ]
