# Generated by Django 5.0.7 on 2025-05-12 10:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutomazioneDati', '0037_remove_regsegnanti_impianto_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letturacontatore',
            name='a1_pos',
            field=models.DecimalField(blank=True, decimal_places=3, default=Decimal('0.0'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='letturacontatore',
            name='a2_pos',
            field=models.DecimalField(blank=True, decimal_places=3, default=Decimal('0.0'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='letturacontatore',
            name='a3_pos',
            field=models.DecimalField(blank=True, decimal_places=3, default=Decimal('0.0'), max_digits=10),
        ),
    ]
