# Generated by Django 5.0.7 on 2025-05-12 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutomazioneDati', '0039_letturacontatore_autocons_campo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letturacontatore',
            name='autocons_campo',
        ),
        migrations.RemoveField(
            model_name='letturacontatore',
            name='autocons_ed',
        ),
        migrations.RemoveField(
            model_name='letturacontatore',
            name='autocons_gse',
        ),
        migrations.RemoveField(
            model_name='letturacontatore',
            name='imm_campo',
        ),
        migrations.RemoveField(
            model_name='letturacontatore',
            name='imm_ed',
        ),
        migrations.RemoveField(
            model_name='letturacontatore',
            name='imm_gse',
        ),
        migrations.RemoveField(
            model_name='letturacontatore',
            name='prel_campo',
        ),
        migrations.RemoveField(
            model_name='letturacontatore',
            name='prel_ed',
        ),
        migrations.RemoveField(
            model_name='letturacontatore',
            name='prel_gse',
        ),
        migrations.RemoveField(
            model_name='letturacontatore',
            name='prod_campo',
        ),
        migrations.RemoveField(
            model_name='letturacontatore',
            name='prod_ed',
        ),
        migrations.RemoveField(
            model_name='letturacontatore',
            name='prod_gse',
        ),
        migrations.AlterField(
            model_name='letturacontatore',
            name='contatore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letture', to='AutomazioneDati.contatore'),
        ),
    ]
