# Generated by Django 5.0.7 on 2025-05-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutomazioneDati', '0043_alter_contatore_impianto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='regsegnanti',
            name='impianto_nickname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
