# Generated by Django 5.0.7 on 2025-05-12 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AutomazioneDati', '0044_regsegnanti_impianto_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regsegnanti',
            name='impianto_nickname',
        ),
    ]
