# Generated by Django 5.0.7 on 2025-05-13 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutomazioneDati', '0046_alter_contatore_impianto'),
    ]

    operations = [
        migrations.AddField(
            model_name='letturacontatore',
            name='ora_lettura',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
