# Generated by Django 5.0.7 on 2025-05-28 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutomazioneDati', '0048_remove_letturacontatore_ora_lettura'),
    ]

    operations = [
        migrations.AddField(
            model_name='contatore',
            name='matricola',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contatore',
            name='tipologiafascio',
            field=models.CharField(blank=True, choices=[('Monofascio', 'Monofascio'), ('Trifascio', 'Trifascio')], max_length=20, null=True),
        ),
    ]
