# Generated by Django 5.0.7 on 2025-05-28 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutomazioneDati', '0049_contatore_matricola_contatore_tipologiafascio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letturacontatore',
            name='tipo_tabella',
            field=models.CharField(choices=[('Monofascio', 'Monofascio'), ('Trifascio', 'Trifascio')], max_length=20),
        ),
    ]
