# Generated by Django 5.2.2 on 2025-06-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutomazioneDati', '0057_remove_contatore_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='contatore',
            name='marca',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
