# Generated by Django 5.0.7 on 2025-07-04 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AutomazioneDati', '0059_alter_letturacontatore_a1_pos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regsegnanti',
            name='prel_gse',
        ),
    ]
