# Generated by Django 5.0.7 on 2025-05-15 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PortaleCorrispettivi', '0015_datimensilitabella_media_pun_mensile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datimensilitabella',
            name='media_pun_mensile',
        ),
    ]
