# Generated by Django 5.0.7 on 2024-07-18 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Impianto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(help_text="Identifica l'impianto", max_length=50, unique=True, verbose_name='Nickname')),
                ('societa', models.CharField(blank=True, help_text='Fiscale impianto', max_length=150, null=True, verbose_name='Società')),
                ('nome_impianto', models.CharField(help_text="Nome dell'impianto", max_length=150, verbose_name='Nome')),
                ('tag', models.CharField(help_text='Tag di abbreviazione', max_length=10, verbose_name='Tag')),
                ('tipo', models.CharField(help_text="Tipologia dell'impianto elettrico", max_length=150, verbose_name='Tipo')),
                ('lat', models.FloatField(blank=True, help_text='Latitudine', null=True, verbose_name='Latitudine')),
                ('lon', models.FloatField(blank=True, help_text='Longitudine', null=True, verbose_name='Longitudine')),
                ('localita', models.CharField(blank=True, help_text='Località', max_length=150, null=True, verbose_name='Località')),
                ('unita_misura', models.CharField(blank=True, help_text='Unita misura portata (mc/s o l/s)', max_length=150, null=True, verbose_name='Unita misura')),
                ('portata_concessione', models.FloatField(blank=True, help_text='Portata di concessione', null=True, verbose_name='Portata')),
                ('salto', models.FloatField(blank=True, help_text='Salto impianto', null=True, verbose_name='Salto')),
                ('potenza_installata', models.FloatField(blank=True, help_text='Potenza installata', null=True, verbose_name='Potenza')),
                ('inizio_esercizio', models.DateField(blank=True, help_text='Data inizio esercizio', null=True, verbose_name='Entrata in esercizio')),
                ('lettura_dati', models.CharField(blank=True, help_text='Tipo lettura dati impianti', max_length=50, null=True, verbose_name='Lettura dati')),
                ('proprieta', models.BooleanField(default=False, help_text="Indica se l'impianto è di propietà Zilio", verbose_name='Proprietà')),
            ],
            options={
                'verbose_name': 'Impianto',
                'verbose_name_plural': 'Impianti',
            },
        ),
        migrations.CreateModel(
            name='FileMonitoraggio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartella', models.CharField(help_text='Cartella', max_length=150, verbose_name='Cartella')),
                ('tipo', models.CharField(help_text='Tipo', max_length=50, verbose_name='Tipo')),
                ('impianto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MonitoraggioImpianti.impianto')),
            ],
            options={
                'verbose_name': 'File Monitoraggio',
                'verbose_name_plural': 'File Monitoraggio',
            },
        ),
        migrations.CreateModel(
            name='InfoStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variabile', models.CharField(help_text='Variabile di riferimento', max_length=50, verbose_name='Variabile')),
                ('valore', models.FloatField(blank=True, help_text='Valore', null=True, verbose_name='Valore')),
                ('impianto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MonitoraggioImpianti.impianto')),
            ],
            options={
                'verbose_name': 'Statistica variabili',
                'verbose_name_plural': 'Statistiche variabili',
            },
        ),
    ]
