# Generated by Django 5.0.7 on 2024-08-20 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonitoraggioImpianti', '0004_linkportale'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkportale',
            name='tag',
            field=models.CharField(default='-', max_length=50, verbose_name='tag portale'),
        ),
    ]
