# Generated by Django 5.0.7 on 2026-03-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonitoraggioImpianti', '0005_linkportale_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='impianto',
            name='energia_annua_kwh',
            field=models.FloatField(blank=True, help_text='Energia annua prodotta in kWh', null=True, verbose_name='Energia annua [kWh]'),
        ),
        migrations.AddField(
            model_name='impianto',
            name='ha_meteo_station',
            field=models.BooleanField(blank=True, help_text="Indica se l'impianto dispone di una meteo station ISC", null=True, verbose_name='Meteo station disponibile'),
        ),
        migrations.AddField(
            model_name='impianto',
            name='irraggiamento_annuo_kwh_m2',
            field=models.FloatField(blank=True, help_text='Irraggiamento annuo sul piano moduli in kWh/m2', null=True, verbose_name='Irraggiamento annuo [kWh/m2]'),
        ),
        migrations.AddField(
            model_name='impianto',
            name='ore_equivalenti_annue',
            field=models.FloatField(blank=True, help_text='Ore equivalenti annue', null=True, verbose_name='Ore equivalenti annue'),
        ),
        migrations.AddField(
            model_name='impianto',
            name='ore_equivalenti_giornaliere',
            field=models.FloatField(blank=True, help_text='Ore equivalenti giornaliere', null=True, verbose_name='Ore equivalenti giornaliere'),
        ),
        migrations.AddField(
            model_name='impianto',
            name='ore_equivalenti_totali',
            field=models.FloatField(blank=True, help_text='Ore equivalenti totali', null=True, verbose_name='Ore equivalenti totali'),
        ),
        migrations.AddField(
            model_name='impianto',
            name='performance_ratio_annuo',
            field=models.FloatField(blank=True, help_text="Performance ratio annuo dell'impianto", null=True, verbose_name='PR annuo'),
        ),
        migrations.AddField(
            model_name='impianto',
            name='stato_operativo',
            field=models.CharField(blank=True, help_text='Stato operativo impianto', max_length=50, null=True, verbose_name='Stato operativo'),
        ),
    ]
