# Generated by Django 5.0.7 on 2026-03-13 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonitoraggioImpianti', '0006_impianto_energia_annua_kwh_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='impianto',
            name='ha_meteo_station',
            field=models.BooleanField(blank=True, help_text="Indica se l'impianto dispone di una meteo station ISC", null=True, verbose_name='Meteo station disponibile'),
        ),
        migrations.AddField(
            model_name='impianto',
            name='irraggiamento_annuo_kwh_m2',
            field=models.FloatField(blank=True, help_text='Irraggiamento annuo sul piano moduli in kWh/m2', null=True, verbose_name='Irraggiamento annuo [kWh/m2]'),
        ),
        migrations.AddField(
            model_name='impianto',
            name='performance_ratio_annuo',
            field=models.FloatField(blank=True, help_text="Performance ratio annuo dell'impianto", null=True, verbose_name='PR annuo'),
        ),
    ]
