# Generated by Django 5.0.7 on 2026-04-16 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MonitoraggioImpianti', '0006_impianto_energia_annua_kwh_impianto_ha_meteo_station_and_more'),
    ]

    operations = [
    ]
