# Generated by Django 5.0.7 on 2026-05-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonitoraggioImpianti', '0008_merge_20260416_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='impianto',
            name='max_gauge_portata',
            field=models.FloatField(blank=True, help_text='Valore massimo personalizzato per il gauge portata. Se vuoto, usa la logica automatica.', null=True, verbose_name='Max gauge portata'),
        ),
        migrations.AlterField(
            model_name='impianto',
            name='portata_concessione',
            field=models.FloatField(blank=True, help_text='Portata di concessione in m3/s', null=True, verbose_name='Portata'),
        ),
    ]
