# Generated by Django 5.0.7 on 2026-03-10 08:06

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MonitoraggioImpianti', '0005_linkportale_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoraggioImpianto',
            fields=[
            ],
            options={
                'verbose_name': 'Monitoraggio Impianto',
                'verbose_name_plural': 'Monitoraggi Impianti',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('MonitoraggioImpianti.impianto',),
        ),
    ]
