# Generated by Codex on 2026-03-10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonitoraggioImpianti', '0005_linkportale_tag'),
        ('PortaleZilioService', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FvMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_impianto', models.CharField(max_length=150)),
                ('potenza', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('categoria_fv', models.CharField(choices=[('CLIENTE', 'Cliente'), ('PROPRIETA', 'Proprieta')], max_length=20)),
                ('is_ppu', models.BooleanField(default=False)),
                ('is_in_costruzione', models.BooleanField(default=False)),
                ('data_inizio_contratto', models.DateField(blank=True, null=True)),
                ('data_fine_contratto', models.DateField(blank=True, null=True)),
                ('pr_contrattuale', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('impianto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fv_metadata', to='MonitoraggioImpianti.impianto')),
            ],
            options={
                'verbose_name': 'FV Metadata',
                'verbose_name_plural': 'FV Metadata',
                'db_table': 'fv_metadata',
            },
        ),
        migrations.AddConstraint(
            model_name='fvmetadata',
            constraint=models.CheckConstraint(
                check=(
                    models.Q(data_fine_contratto__isnull=True)
                    | models.Q(data_inizio_contratto__isnull=True)
                    | models.Q(data_fine_contratto__gte=models.F('data_inizio_contratto'))
                ),
                name='ck_fv_metadata_contract_dates',
            ),
        ),
    ]
