# Generated by Django 5.0.7 on 2026-03-24 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortaleZilioService', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpiantoAnagrafica',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_impianto', models.CharField(max_length=150)),
                ('tag_impianto', models.CharField(max_length=30, unique=True)),
                ('codice_impianto', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('tipo_impianto', models.CharField(choices=[('fotovoltaico', 'Fotovoltaico'), ('idroelettrico', 'Idroelettrico')], max_length=50)),
                ('stato_impianto', models.CharField(choices=[('attivo', 'Attivo'), ('in_costruzione', 'In costruzione'), ('sospeso', 'Sospeso'), ('dismesso', 'Dismesso'), ('unknown', 'Unknown')], default='unknown', max_length=50)),
                ('latitudine', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('longitudine', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('indirizzo', models.CharField(blank=True, max_length=255, null=True)),
                ('localita', models.CharField(blank=True, max_length=150, null=True)),
                ('provincia', models.CharField(blank=True, max_length=50, null=True)),
                ('regione', models.CharField(blank=True, max_length=50, null=True)),
                ('potenza_installata_kw', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('data_entrata_esercizio', models.DateField(blank=True, null=True)),
                ('nome_proprietario', models.CharField(blank=True, max_length=150, null=True)),
                ('nome_cliente', models.CharField(blank=True, max_length=150, null=True)),
                ('attivo_portale', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Impianto anagrafica',
                'verbose_name_plural': 'Impianti anagrafica',
                'ordering': ['nome_impianto'],
            },
        ),
        migrations.CreateModel(
            name='IdroelettricoMetadata',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('categoria_idr', models.CharField(choices=[('proprieta', 'Proprietà'), ('gse', 'GSE'), ('unknown', 'Unknown')], max_length=30)),
                ('portata_concessione', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('unita_misura_portata', models.CharField(blank=True, max_length=20, null=True)),
                ('salto', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('potenza_business_plan_kw', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('note_idroelettrico', models.TextField(blank=True, null=True)),
                ('impianto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='idroelettrico_metadata', to='PortaleZilioService.impiantoanagrafica')),
            ],
            options={
                'verbose_name': 'Metadata idroelettrico',
                'verbose_name_plural': 'Metadata idroelettrico',
            },
        ),
        migrations.CreateModel(
            name='FotovoltaicoStatoEconomico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inizio_contratto', models.DateField(blank=True, null=True)),
                ('data_fine_contratto', models.DateField(blank=True, null=True)),
                ('totale_contratto', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('anni_contratto', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('totale_annuale_su_mw', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('totale_annuo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('maturato', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fatturato', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('incassato', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('data_prossima_fattura', models.DateField(blank=True, null=True)),
                ('importo_prossima_fattura', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('costo_sostenuto_straordinario', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('totale_fatturato_straordinario', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('margine_straordinario', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('numero_fatture_straordinarie_annuo', models.PositiveIntegerField(blank=True, null=True)),
                ('numero_fatture_straordinarie_totali', models.PositiveIntegerField(blank=True, null=True)),
                ('last_api_sync_at', models.DateTimeField(blank=True, null=True)),
                ('api_sync_status', models.CharField(choices=[('never', 'Mai sincronizzato'), ('ok', 'OK'), ('partial', 'Parziale'), ('error', 'Errore')], default='never', max_length=20)),
                ('api_sync_note', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('impianto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fotovoltaico_stato_economico', to='PortaleZilioService.impiantoanagrafica')),
            ],
            options={
                'verbose_name': 'Stato economico fotovoltaico',
                'verbose_name_plural': 'Stati economici fotovoltaici',
                'ordering': ['impianto__nome_impianto'],
            },
        ),
        migrations.CreateModel(
            name='FotovoltaicoMetricheTecniche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_ultimi_12_mesi', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('mancata_produzione', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ore_equivalenti_ultimi_12_mesi', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stato_operativo', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('warning', 'Warning'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(choices=[('never', 'Mai sincronizzato'), ('ok', 'OK'), ('partial', 'Parziale'), ('error', 'Errore')], default='never', max_length=20)),
                ('sync_note', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('impianto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fotovoltaico_metriche_tecniche', to='PortaleZilioService.impiantoanagrafica')),
            ],
            options={
                'verbose_name': 'Metriche tecniche fotovoltaico',
                'verbose_name_plural': 'Metriche tecniche fotovoltaico',
                'ordering': ['impianto__nome_impianto'],
            },
        ),
        migrations.CreateModel(
            name='FotovoltaicoMetadata',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('categoria_fv', models.CharField(choices=[('cliente', 'Cliente'), ('proprieta', 'Proprietà')], max_length=30)),
                ('is_ppu', models.BooleanField(default=False)),
                ('is_agrivoltaico', models.BooleanField(default=False)),
                ('pr_contrattuale', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('note_fotovoltaico', models.TextField(blank=True, null=True)),
                ('impianto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fotovoltaico_metadata', to='PortaleZilioService.impiantoanagrafica')),
            ],
            options={
                'verbose_name': 'Metadata fotovoltaico',
                'verbose_name_plural': 'Metadata fotovoltaico',
            },
        ),
        migrations.CreateModel(
            name='ImpiantoDispositivo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_dispositivo', models.CharField(choices=[('inverter', 'Inverter'), ('storage_inverter', 'Storage inverter'), ('weather_station', 'Weather station')], max_length=50)),
                ('codice_dispositivo', models.CharField(max_length=100)),
                ('attivo', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('impianto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivi', to='PortaleZilioService.impiantoanagrafica')),
            ],
            options={
                'verbose_name': 'Dispositivo impianto',
                'verbose_name_plural': 'Dispositivi impianto',
                'ordering': ['impianto__nome_impianto', 'tipo_dispositivo', 'codice_dispositivo'],
            },
        ),
        migrations.CreateModel(
            name='ImpiantoSorgenteDati',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_sorgente', models.CharField(choices=[('monitoraggio_tecnico', 'Monitoraggio tecnico'), ('amministrativa', 'Amministrativa'), ('gse', 'GSE'), ('altro', 'Altro')], max_length=50)),
                ('nome_sorgente', models.CharField(max_length=100)),
                ('identificativo_esterno', models.CharField(blank=True, max_length=100, null=True)),
                ('nome_riferimento_esterno', models.CharField(blank=True, max_length=150, null=True)),
                ('attiva', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('impianto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sorgenti_dati', to='PortaleZilioService.impiantoanagrafica')),
            ],
            options={
                'verbose_name': 'Sorgente dati impianto',
                'verbose_name_plural': 'Sorgenti dati impianto',
                'ordering': ['impianto__nome_impianto', 'tipo_sorgente', 'nome_sorgente'],
            },
        ),
        migrations.AddConstraint(
            model_name='fotovoltaicostatoeconomico',
            constraint=models.CheckConstraint(check=models.Q(('data_fine_contratto__isnull', True), ('data_inizio_contratto__isnull', True), ('data_fine_contratto__gte', models.F('data_inizio_contratto')), _connector='OR'), name='ck_fv_stato_economico_contract_dates'),
        ),
        migrations.AlterUniqueTogether(
            name='impiantodispositivo',
            unique_together={('impianto', 'codice_dispositivo')},
        ),
    ]
