# Generated by Codex on 2026-03-10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonitoraggioImpianti', '0005_linkportale_tag'),
        ('PortaleZilioService', '0002_fvmetadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='fvmetadata',
            name='nome_cliente',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='fvmetadata',
            name='nome_proprietario',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='fvmetadata',
            name='impianto',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='fv_metadata',
                to='MonitoraggioImpianti.impianto',
            ),
        ),
    ]
