# Generated by Django 5.2.10 on 2026-03-27 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortaleZilioService', '0002_impiantoanagrafica_idroelettricometadata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotovoltaicometadata',
            name='is_oem',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fotovoltaicostatoeconomico',
            name='importo_stimato_contratto_annuo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
