# Generated by Django 5.0.7 on 2026-03-19 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortaleZilioService', '0003_fvmetadata_nome_fields_and_optional_impianto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpiantoAnagrafica',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_impianto', models.CharField(max_length=150)),
                ('tag_impianto', models.CharField(max_length=30, unique=True)),
                ('tipo_impianto', models.CharField(choices=[('fotovoltaico', 'Fotovoltaico'), ('idroelettrico', 'Idroelettrico')], max_length=50)),
                ('stato_impianto', models.CharField(choices=[('attivo', 'Attivo'), ('in_costruzione', 'In costruzione'), ('sospeso', 'Sospeso'), ('dismesso', 'Dismesso'), ('unknown', 'Unknown')], default='unknown', max_length=50)),
                ('latitudine', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('longitudine', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('indirizzo', models.CharField(blank=True, max_length=255, null=True)),
                ('localita', models.CharField(blank=True, max_length=150, null=True)),
                ('provincia', models.CharField(blank=True, max_length=50, null=True)),
                ('regione', models.CharField(blank=True, max_length=50, null=True)),
                ('potenza_installata_kw', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('data_entrata_esercizio', models.DateField(blank=True, null=True)),
                ('nome_proprietario', models.CharField(blank=True, max_length=150, null=True)),
                ('nome_cliente', models.CharField(blank=True, max_length=150, null=True)),
                ('attivo_portale', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Impianto anagrafica',
                'verbose_name_plural': 'Impianti anagrafica',
                'ordering': ['nome_impianto'],
            },
        ),
        migrations.CreateModel(
            name='IdroelettricoMetadata',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('categoria_idr', models.CharField(choices=[('oem_proprieta', 'O&M Proprietà'), ('gse', 'GSE')], max_length=30)),
                ('portata_concessione', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('unita_misura_portata', models.CharField(blank=True, max_length=20, null=True)),
                ('salto', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('potenza_business_plan_kw', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('note_idroelettrico', models.TextField(blank=True, null=True)),
                ('impianto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='idroelettrico_metadata', to='PortaleZilioService.impiantoanagrafica')),
            ],
            options={
                'verbose_name': 'Metadata idroelettrico',
                'verbose_name_plural': 'Metadata idroelettrico',
            },
        ),
        migrations.CreateModel(
            name='FotovoltaicoMetadata',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('categoria_fv', models.CharField(choices=[('cliente', 'Cliente'), ('proprieta', 'Proprietà')], max_length=30)),
                ('is_ppu', models.BooleanField(default=False)),
                ('is_agrivoltaico', models.BooleanField(default=False)),
                ('pr_contrattuale', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('note_fotovoltaico', models.TextField(blank=True, null=True)),
                ('impianto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fotovoltaico_metadata', to='PortaleZilioService.impiantoanagrafica')),
            ],
            options={
                'verbose_name': 'Metadata fotovoltaico',
                'verbose_name_plural': 'Metadata fotovoltaico',
            },
        ),
        migrations.CreateModel(
            name='ImpiantoDispositivo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_dispositivo', models.CharField(choices=[('inverter', 'Inverter'), ('weather_station', 'Weather station')], max_length=50)),
                ('nome_dispositivo', models.CharField(blank=True, max_length=150, null=True)),
                ('identificativo_esterno', models.CharField(max_length=100)),
                ('attivo', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('impianto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivi', to='PortaleZilioService.impiantoanagrafica')),
            ],
            options={
                'verbose_name': 'Dispositivo impianto',
                'verbose_name_plural': 'Dispositivi impianto',
                'ordering': ['impianto__nome_impianto', 'tipo_dispositivo', 'identificativo_esterno'],
            },
        ),
        migrations.CreateModel(
            name='ImpiantoSorgenteDati',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_sorgente', models.CharField(choices=[('monitoraggio_tecnico', 'Monitoraggio tecnico'), ('amministrativa', 'Amministrativa'), ('gse', 'GSE'), ('altro', 'Altro')], max_length=50)),
                ('nome_sorgente', models.CharField(max_length=100)),
                ('identificativo_esterno', models.CharField(blank=True, max_length=100, null=True)),
                ('nome_riferimento_esterno', models.CharField(blank=True, max_length=150, null=True)),
                ('attiva', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('impianto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sorgenti_dati', to='PortaleZilioService.impiantoanagrafica')),
            ],
            options={
                'verbose_name': 'Sorgente dati impianto',
                'verbose_name_plural': 'Sorgenti dati impianto',
                'ordering': ['impianto__nome_impianto', 'tipo_sorgente', 'nome_sorgente'],
            },
        ),
    ]
