# Generated by Django 5.2.10 on 2026-03-27 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortaleZilioService', '0003_fotovoltaicometadata_is_oem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotovoltaicometadata',
            name='potenza_contratto_kw',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
