# Generated by Django 5.0.7 on 2026-03-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortaleZilioService', '0004_impiantoanagrafica_idroelettricometadata_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='impiantodispositivo',
            options={'ordering': ['impianto__nome_impianto', 'tipo_dispositivo', 'codice_dispositivo'], 'verbose_name': 'Dispositivo impianto', 'verbose_name_plural': 'Dispositivi impianto'},
        ),
        migrations.RenameField(
            model_name='impiantodispositivo',
            old_name='identificativo_esterno',
            new_name='codice_dispositivo',
        ),
        migrations.AlterUniqueTogether(
            name='impiantodispositivo',
            unique_together={('impianto', 'codice_dispositivo')},
        ),
        migrations.AddField(
            model_name='impiantoanagrafica',
            name='codice_impianto',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='idroelettricometadata',
            name='categoria_idr',
            field=models.CharField(choices=[('proprieta', 'Proprietà'), ('gse', 'GSE'), ('unknown', 'Unknown')], max_length=30),
        ),
        migrations.RemoveField(
            model_name='impiantodispositivo',
            name='nome_dispositivo',
        ),
    ]
