# Generated by Django 5.0.7 on 2026-03-20 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortaleZilioService', '0005_alter_impiantodispositivo_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotovoltaicoMetricheTecniche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_ultimi_12_mesi', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('mancata_produzione', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ore_equivalenti_ultimi_12_mesi', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(choices=[('never', 'Mai sincronizzato'), ('ok', 'OK'), ('partial', 'Parziale'), ('error', 'Errore')], default='never', max_length=20)),
                ('sync_note', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('impianto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fotovoltaico_metriche_tecniche', to='PortaleZilioService.impiantoanagrafica')),
            ],
            options={
                'verbose_name': 'Metriche tecniche fotovoltaico',
                'verbose_name_plural': 'Metriche tecniche fotovoltaico',
                'ordering': ['impianto__nome_impianto'],
            },
        ),
        migrations.CreateModel(
            name='FotovoltaicoStatoEconomico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inizio_contratto', models.DateField(blank=True, null=True)),
                ('data_fine_contratto', models.DateField(blank=True, null=True)),
                ('totale_contratto', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('anni_contratto', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('totale_annuale_su_mw', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('totale_annuo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('maturato', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fatturato', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('incassato', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('data_prossima_fattura', models.DateField(blank=True, null=True)),
                ('importo_prossima_fattura', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('costo_sostenuto_straordinario', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('totale_fatturato_straordinario', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('margine_straordinario', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('numero_fatture_straordinarie_annuo', models.PositiveIntegerField(blank=True, null=True)),
                ('numero_fatture_straordinarie_totali', models.PositiveIntegerField(blank=True, null=True)),
                ('last_api_sync_at', models.DateTimeField(blank=True, null=True)),
                ('api_sync_status', models.CharField(choices=[('never', 'Mai sincronizzato'), ('ok', 'OK'), ('partial', 'Parziale'), ('error', 'Errore')], default='never', max_length=20)),
                ('api_sync_note', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('impianto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fotovoltaico_stato_economico', to='PortaleZilioService.impiantoanagrafica')),
            ],
            options={
                'verbose_name': 'Stato economico fotovoltaico',
                'verbose_name_plural': 'Stati economici fotovoltaici',
                'ordering': ['impianto__nome_impianto'],
            },
        ),
        migrations.AddConstraint(
            model_name='fotovoltaicostatoeconomico',
            constraint=models.CheckConstraint(check=models.Q(('data_fine_contratto__isnull', True), ('data_inizio_contratto__isnull', True), ('data_fine_contratto__gte', models.F('data_inizio_contratto')), _connector='OR'), name='ck_fv_stato_economico_contract_dates'),
        ),
    ]
