# Generated by Django 5.0.7 on 2026-04-09 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortaleZilioService', '0006_fotovoltaicometrichetecniche_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotovoltaicostatoeconomico',
            name='importo_canone_periodico',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Importo del singolo canone relativo alla periodicita indicata in 'periodicita_canone_mesi'.", max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='fotovoltaicostatoeconomico',
            name='periodicita_canone_mesi',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Periodicita del canone espressa in mesi. Ad esempio: 1=mensile, 3=trimestrale, 6=semestrale, 12=annuale.', null=True),
        ),
        migrations.AddConstraint(
            model_name='fotovoltaicostatoeconomico',
            constraint=models.CheckConstraint(check=models.Q(('periodicita_canone_mesi__isnull', True), ('periodicita_canone_mesi__gt', 0), _connector='OR'), name='ck_fv_stato_economico_periodicita_canone_positive'),
        ),
        migrations.AddConstraint(
            model_name='fotovoltaicostatoeconomico',
            constraint=models.CheckConstraint(check=models.Q(('importo_canone_periodico__isnull', True), ('importo_canone_periodico__gte', 0), _connector='OR'), name='ck_fv_stato_economico_importo_canone_non_negative'),
        ),
    ]
