# Generated by Django 5.0.7 on 2026-03-23 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortaleZilioService', '0007_fvmetadata_contract_totals'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotovoltaicometrichetecniche',
            name='stato_operativo',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('warning', 'Warning'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='impiantodispositivo',
            name='tipo_dispositivo',
            field=models.CharField(choices=[('inverter', 'Inverter'), ('storage_inverter', 'Storage inverter'), ('weather_station', 'Weather station')], max_length=50),
        ),
    ]
