# Generated by Django 5.0.7 on 2026-03-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PortaleZilioService", "0008_fotovoltaicometrichetecniche_stato_operativo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fotovoltaicostatoeconomico",
            name="importo_stimato_contratto_annuo",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
