# Generated by Django 5.0.7 on 2026-03-27 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PortaleZilioService", "0009_fotovoltaicostatoeconomico_importo_stimato_contratto_annuo"),
    ]

    operations = [
        migrations.AddField(
            model_name="fotovoltaicometadata",
            name="is_oem",
            field=models.BooleanField(default=False),
        ),
    ]
