# Generated by Django 5.0.7 on 2026-03-27 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PortaleZilioService", "0010_fotovoltaicometadata_is_oem"),
    ]

    operations = [
        migrations.AddField(
            model_name="fotovoltaicometadata",
            name="potenza_contratto_kw",
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
