# Generated by Django 5.0.7 on 2026-04-02 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortaleZilioService', '0015_alter_impiantoanagrafica_stato_impianto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impiantoanagrafica',
            name='codice_riferimento_commessa',
        ),
        migrations.CreateModel(
            name='ImpiantoCommessa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_commessa', models.CharField(choices=[('oem', 'O&M'), ('ppu', 'PPU'), ('str', 'Straordinario')], max_length=20)),
                ('codice_commessa', models.CharField(max_length=50)),
                ('note', models.TextField(blank=True, null=True)),
                ('impianto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commesse', to='PortaleZilioService.impiantoanagrafica')),
            ],
            options={
                'verbose_name': 'Commessa impianto',
                'verbose_name_plural': 'Commesse impianto',
                'ordering': ['impianto__nome_impianto', 'tipo_commessa'],
                'unique_together': {('impianto', 'tipo_commessa', 'codice_commessa')},
            },
        ),
    ]
