# Generated by Django 5.0.7 on 2026-04-15 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortaleZilioService', '0017_fotovoltaicostatoeconomico_canone_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoImpianto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documenti_impianto/')),
                ('descrizione', models.CharField(blank=True, max_length=255)),
                ('impianto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documenti', to='PortaleZilioService.impiantoanagrafica')),
            ],
            options={
                'verbose_name': 'Documento impianto',
                'verbose_name_plural': 'Documenti impianto',
                'ordering': ['impianto__nome_impianto', 'descrizione'],
            },
        ),
    ]
