# Generated by Django 5.0.7 on 2026-04-16 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PortaleZilioService', '0007_fotovoltaicostatoeconomico_importo_canone_periodico_and_more'),
        ('PortaleZilioService', '0019_impiantocommessa_riparto_and_seed'),
    ]

    operations = [
    ]
