# Generated by Django 5.0.7 on 2026-04-16 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortaleZilioService', '0020_merge_20260416_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='impiantocommessa',
            name='riparto',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
    ]
