# Generated by Django 5.0.7 on 2026-05-26 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortaleZilioService', '0021_impiantocommessa_riparto'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotovoltaicostatoeconomico',
            name='tariffa_ppu_mwh',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Tariffa PPU (EUR/MWh)'),
        ),
    ]
