# Generated by Django 5.0.7 on 2026-05-26 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortaleZilioService', '0022_fotovoltaicostatoeconomico_tariffa_ppu_mwh'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotovoltaicostatoeconomico',
            name='strumento_contabilizzazione_ppu',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Strumento di contabilizzazione PPU'),
        ),
    ]
