# Generated by Django 5.0.7 on 2026-05-26 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortaleZilioService', '0023_fotovoltaicostatoeconomico_strumento_contabilizzazione_ppu'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotovoltaicostatoeconomico',
            name='tipologia_pagamento_ppu',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tipologia di pagamento PPU'),
        ),
    ]
