# Generated by Django 5.0.7 on 2026-05-26 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortaleZilioService', '0024_fotovoltaicostatoeconomico_tipologia_pagamento_ppu'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotovoltaicometrichetecniche',
            name='energia_prodotta_anno_corrente_kwh',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Energia prodotta anno corrente (kWh)'),
        ),
    ]
