# Generated by Django 5.0.7 on 2026-05-26 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortaleZilioService', '0025_fotovoltaicometrichetecniche_energia_prodotta_anno_corrente_kwh'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotovoltaicometrichetecniche',
            name='energia_prodotta_anno_corrente_aggiornata_al',
            field=models.DateField(blank=True, null=True, verbose_name='Energia prodotta anno corrente aggiornata al'),
        ),
    ]
