# Generated by Django 5.0.7 on 2026-05-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortaleZilioService', '0026_fotovoltaicometrichetecniche_energia_prodotta_anno_corrente_aggiornata_al'),
    ]

    operations = [
        migrations.AddField(
            model_name='impiantodispositivo',
            name='data_fine_monitoraggio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='impiantodispositivo',
            name='data_inizio_monitoraggio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='impiantodispositivo',
            constraint=models.CheckConstraint(check=models.Q(('data_fine_monitoraggio__isnull', True), ('data_inizio_monitoraggio__isnull', True), ('data_fine_monitoraggio__gte', models.F('data_inizio_monitoraggio')), _connector='OR'), name='ck_dispositivo_monitoraggio_dates'),
        ),
    ]
