# Generated by Django 5.0.7 on 2026-05-28 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortaleZilioService', '0027_impiantodispositivo_data_fine_monitoraggio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotovoltaicometrichetecniche',
            name='energia_immessa_anno_corrente_kwh',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Energia immessa in rete anno corrente (kWh)'),
        ),
    ]
