# Generated by Django 5.0.7 on 2026-05-28 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortaleZilioService', '0028_energia_immessa_anno_corrente'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotovoltaicometrichetecniche',
            name='energia_immessa_anno_corrente_aggiornata_al',
            field=models.DateField(blank=True, null=True, verbose_name='Energia immessa anno corrente aggiornata al'),
        ),
    ]
