# Generated by Django 5.0.7 on 2026-05-29 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortaleZilioService', '0029_energia_immessa_aggiornata_al'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotovoltaicometrichetecniche',
            name='energia_stimata_anno_corrente_kwh',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Energia stimata anno corrente (kWh)'),
        ),
    ]
