# Generated by Django 5.0.7 on 2025-04-03 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contatore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impianto_nickname', models.CharField(max_length=50)),
                ('nome_impianto', models.CharField(max_length=100)),
                ('nome', models.CharField(max_length=100)),
                ('pod', models.CharField(max_length=50)),
                ('tipologia', models.CharField(choices=[('Produzione', 'Produzione'), ('Scambio', 'Scambio'), ('Ausiliare', 'Ausiliare')], max_length=20)),
                ('k', models.IntegerField()),
                ('marca', models.CharField(choices=[('Kaifa', 'Kaifa'), ('Gesis', 'Gesis')], max_length=20)),
                ('modello', models.CharField(max_length=50)),
                ('data_installazione', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Impianto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_impianto', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LetturaContatore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anno', models.IntegerField()),
                ('mese', models.IntegerField()),
                ('tipo_tabella', models.CharField(max_length=20)),
                ('prod_campo', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('prod_ed', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('prod_gse', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('prel_campo', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('prel_ed', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('prel_gse', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('imm_campo', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('imm_ed', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('imm_gse', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('data_presa', models.DateField(blank=True, null=True)),
                ('a1_neg', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('a2_neg', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('a3_neg', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('totale_neg', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('a1_pos', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('a2_pos', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('a3_pos', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('totale_pos', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('kaifa_180n', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('kaifa_280n', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('contatore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letture', to='AutomazioneDati.contatore')),
            ],
            options={
                'unique_together': {('contatore', 'anno', 'mese', 'tipo_tabella')},
            },
        ),
    ]
