# Generated by Django 5.0.7 on 2025-04-03 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutomazioneDati', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letturacontatore',
            name='a1_neg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='letturacontatore',
            name='a1_pos',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='letturacontatore',
            name='a2_neg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='letturacontatore',
            name='a2_pos',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='letturacontatore',
            name='a3_neg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='letturacontatore',
            name='a3_pos',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='letturacontatore',
            name='anno',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='letturacontatore',
            name='contatore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AutomazioneDati.contatore'),
        ),
        migrations.AlterField(
            model_name='letturacontatore',
            name='imm_campo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='letturacontatore',
            name='imm_ed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='letturacontatore',
            name='imm_gse',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='letturacontatore',
            name='kaifa_180n',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='letturacontatore',
            name='kaifa_280n',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='letturacontatore',
            name='mese',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='letturacontatore',
            name='prel_campo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='letturacontatore',
            name='prel_ed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='letturacontatore',
            name='prel_gse',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='letturacontatore',
            name='prod_campo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='letturacontatore',
            name='prod_ed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='letturacontatore',
            name='prod_gse',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='letturacontatore',
            name='totale_neg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='letturacontatore',
            name='totale_pos',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
