# Generated by Django 5.0.7 on 2025-04-03 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutomazioneDati', '0002_alter_letturacontatore_a1_neg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contatore',
            name='nome_impianto',
        ),
        migrations.AddField(
            model_name='contatore',
            name='impianto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contatori', to='AutomazioneDati.impianto'),
        ),
        migrations.AlterField(
            model_name='contatore',
            name='impianto_nickname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='letturacontatore',
            name='a1_neg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='letturacontatore',
            name='a1_pos',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='letturacontatore',
            name='a2_neg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='letturacontatore',
            name='a2_pos',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='letturacontatore',
            name='a3_neg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='letturacontatore',
            name='a3_pos',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='letturacontatore',
            name='anno',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='letturacontatore',
            name='contatore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letture', to='AutomazioneDati.contatore'),
        ),
        migrations.AlterField(
            model_name='letturacontatore',
            name='imm_campo',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='letturacontatore',
            name='imm_ed',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='letturacontatore',
            name='imm_gse',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='letturacontatore',
            name='kaifa_180n',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='letturacontatore',
            name='kaifa_280n',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='letturacontatore',
            name='mese',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='letturacontatore',
            name='prel_campo',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='letturacontatore',
            name='prel_ed',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='letturacontatore',
            name='prel_gse',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='letturacontatore',
            name='prod_campo',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='letturacontatore',
            name='prod_ed',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='letturacontatore',
            name='prod_gse',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='letturacontatore',
            name='totale_neg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='letturacontatore',
            name='totale_pos',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
