# Generated by Django 5.0.7 on 2025-04-08 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutomazioneDati', '0005_remove_letturacontatore_autocons_campo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='letturacontatore',
            name='totale_180n',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='letturacontatore',
            name='totale_280n',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
