# Generated by Django 5.0.7 on 2025-04-09 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutomazioneDati', '0006_letturacontatore_totale_180n_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='letturacontatore',
            name='scambio_prelevata_campo',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='letturacontatore',
            name='scambio_prelevata_ed',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='letturacontatore',
            name='scambio_prelevata_gse',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
