# Generated by Django 5.0.7 on 2025-04-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutomazioneDati', '0007_letturacontatore_scambio_prelevata_campo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='letturacontatore',
            options={'verbose_name': 'Lettura Contatore', 'verbose_name_plural': 'Letture Contatori'},
        ),
        migrations.AddField(
            model_name='letturacontatore',
            name='data_reg',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='letturacontatore',
            name='imm_campo_calcolato',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='Immissione Calcolata (totale_180n * k)'),
        ),
        migrations.AddField(
            model_name='letturacontatore',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='letturacontatore',
            name='prelevata_campo',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='letturacontatore',
            name='kaifa_180n',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='letturacontatore',
            name='kaifa_280n',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='letturacontatore',
            name='prod_campo',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='letturacontatore',
            name='totale_180n',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='letturacontatore',
            name='totale_280n',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
    ]
