# Generated by Django 5.0.7 on 2025-04-10 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AutomazioneDati', '0009_letturacontatore_autocons_campo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letturacontatore',
            name='autocons_campo',
        ),
    ]
