# Generated by Django 5.0.7 on 2025-04-11 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AutomazioneDati', '0010_remove_letturacontatore_autocons_campo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letturacontatore',
            name='imm_campo',
        ),
        migrations.RemoveField(
            model_name='letturacontatore',
            name='imm_ed',
        ),
        migrations.RemoveField(
            model_name='letturacontatore',
            name='imm_gse',
        ),
        migrations.RemoveField(
            model_name='letturacontatore',
            name='prel_campo',
        ),
        migrations.RemoveField(
            model_name='letturacontatore',
            name='prel_ed',
        ),
        migrations.RemoveField(
            model_name='letturacontatore',
            name='prel_gse',
        ),
        migrations.RemoveField(
            model_name='letturacontatore',
            name='prod_ed',
        ),
        migrations.RemoveField(
            model_name='letturacontatore',
            name='prod_gse',
        ),
        migrations.RemoveField(
            model_name='letturacontatore',
            name='scambio_prelevata_campo',
        ),
        migrations.RemoveField(
            model_name='letturacontatore',
            name='scambio_prelevata_ed',
        ),
        migrations.RemoveField(
            model_name='letturacontatore',
            name='scambio_prelevata_gse',
        ),
    ]
