# Generated by Django 5.0.7 on 2025-04-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutomazioneDati', '0011_remove_letturacontatore_imm_campo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contatore',
            name='data_dismissione',
            field=models.DateField(blank=True, null=True),
        ),
    ]
