# Generated by Django 5.0.7 on 2025-04-15 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AutomazioneDati', '0012_contatore_data_dismissione'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contatore',
            name='impianto_nickname',
        ),
    ]
