# Generated by Django 5.0.7 on 2025-04-15 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AutomazioneDati', '0014_contatore_impianto_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letturacontatore',
            name='prelevata_campo',
        ),
        migrations.RemoveField(
            model_name='letturacontatore',
            name='prod_campo',
        ),
    ]
