# Generated by Django 5.0.7 on 2025-04-15 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AutomazioneDati', '0015_remove_letturacontatore_prelevata_campo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letturacontatore',
            name='data_reg',
        ),
        migrations.RemoveField(
            model_name='letturacontatore',
            name='note',
        ),
    ]
