# Generated by Django 5.0.7 on 2025-04-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutomazioneDati', '0016_remove_letturacontatore_data_reg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='letturacontatore',
            name='prel_campo',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='Prelievo Campo (kWh)'),
        ),
        migrations.AddField(
            model_name='letturacontatore',
            name='prel_ed',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='Prelievo e-Distribuzione'),
        ),
        migrations.AddField(
            model_name='letturacontatore',
            name='prel_gse',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='Prelievo G.S.E.'),
        ),
        migrations.AddField(
            model_name='letturacontatore',
            name='prod_campo',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='Produzione/Immissione Campo (kWh)'),
        ),
        migrations.AddField(
            model_name='letturacontatore',
            name='prod_ed',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='Produzione/Immissione e-Distribuzione'),
        ),
        migrations.AddField(
            model_name='letturacontatore',
            name='prod_gse',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='Produzione/Immissione G.S.E.'),
        ),
        migrations.AlterField(
            model_name='letturacontatore',
            name='imm_campo_calcolato',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='Immissione Calcolata (deprecato per reg_segnanti)'),
        ),
    ]
