# Generated by Django 5.0.7 on 2025-04-15 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AutomazioneDati', '0018_remove_letturacontatore_prel_campo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letturacontatore',
            name='data_presa',
        ),
    ]
