# Generated by Django 5.0.7 on 2025-04-16 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutomazioneDati', '0019_remove_letturacontatore_data_presa'),
    ]

    operations = [
        migrations.AddField(
            model_name='letturacontatore',
            name='data_presa',
            field=models.DateField(blank=True, null=True),
        ),
    ]
