# Generated by Django 5.0.7 on 2025-04-18 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AutomazioneDati', '0020_letturacontatore_data_presa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letturacontatore',
            name='data_presa',
        ),
    ]
