# Generated by Django 5.0.7 on 2025-04-22 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutomazioneDati', '0022_letturacontatore_ora_lettura'),
    ]

    operations = [
        migrations.AddField(
            model_name='letturacontatore',
            name='autocons_campo',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='letturacontatore',
            name='autocons_ed',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='letturacontatore',
            name='autocons_gse',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='letturacontatore',
            name='imm_campo',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='letturacontatore',
            name='imm_ed',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='letturacontatore',
            name='imm_gse',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='letturacontatore',
            name='prel_campo',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='letturacontatore',
            name='prel_ed',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='letturacontatore',
            name='prel_gse',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='letturacontatore',
            name='prod_campo',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='letturacontatore',
            name='prod_ed',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='letturacontatore',
            name='prod_gse',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
    ]
