# Generated by Django 5.0.7 on 2025-04-22 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AutomazioneDati', '0023_letturacontatore_autocons_campo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letturacontatore',
            name='autocons_campo',
        ),
        migrations.RemoveField(
            model_name='letturacontatore',
            name='autocons_ed',
        ),
        migrations.RemoveField(
            model_name='letturacontatore',
            name='autocons_gse',
        ),
        migrations.RemoveField(
            model_name='letturacontatore',
            name='imm_campo',
        ),
        migrations.RemoveField(
            model_name='letturacontatore',
            name='imm_ed',
        ),
        migrations.RemoveField(
            model_name='letturacontatore',
            name='imm_gse',
        ),
        migrations.RemoveField(
            model_name='letturacontatore',
            name='prel_campo',
        ),
        migrations.RemoveField(
            model_name='letturacontatore',
            name='prel_ed',
        ),
        migrations.RemoveField(
            model_name='letturacontatore',
            name='prel_gse',
        ),
        migrations.RemoveField(
            model_name='letturacontatore',
            name='prod_campo',
        ),
        migrations.RemoveField(
            model_name='letturacontatore',
            name='prod_ed',
        ),
        migrations.RemoveField(
            model_name='letturacontatore',
            name='prod_gse',
        ),
    ]
