# Generated by Django 5.0.7 on 2025-04-22 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutomazioneDati', '0025_letturacontatore_autocons_campo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='letturacontatore',
            name='data_presa',
            field=models.DateField(blank=True, null=True),
        ),
    ]
