# Generated by Django 5.0.7 on 2025-04-23 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutomazioneDati', '0027_alter_contatore_impianto_delete_impianto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letturacontatore',
            name='data_presa',
        ),
        migrations.RemoveField(
            model_name='letturacontatore',
            name='ora_lettura',
        ),
        migrations.AddField(
            model_name='letturacontatore',
            name='data_ora_lettura',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
