# Generated by Django 5.0.7 on 2025-05-08 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutomazioneDati', '0031_alter_regsegnanti_contatore'),
        ('MonitoraggioImpianti', '0005_linkportale_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='regsegnanti',
            name='impianto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regsegnanti', to='MonitoraggioImpianti.impianto'),
        ),
    ]
