# Generated by Django 5.0.7 on 2025-05-08 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AutomazioneDati', '0032_regsegnanti_impianto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regsegnanti',
            old_name='impianto',
            new_name='impianto_nickname',
        ),
    ]
