# Generated by Django 5.0.7 on 2025-05-08 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutomazioneDati', '0033_rename_impianto_regsegnanti_impianto_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regsegnanti',
            name='impianto_nickname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
