# Generated by Django 5.0.7 on 2025-05-08 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutomazioneDati', '0035_remove_regsegnanti_impianto_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='regsegnanti',
            name='impianto_nickname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
