# Generated by Django 5.0.7 on 2025-05-12 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutomazioneDati', '0040_remove_letturacontatore_autocons_campo_and_more'),
        ('MonitoraggioImpianti', '0005_linkportale_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contatore',
            name='impianto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contatori', to='MonitoraggioImpianti.impianto'),
        ),
    ]
