# Generated by Django 5.0.7 on 2025-05-12 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutomazioneDati', '0041_alter_contatore_impianto'),
        ('MonitoraggioImpianti', '0005_linkportale_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contatore',
            name='impianto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contatori', to='MonitoraggioImpianti.impianto'),
        ),
        migrations.AlterField(
            model_name='letturacontatore',
            name='a1_pos',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='letturacontatore',
            name='a2_pos',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='letturacontatore',
            name='a3_pos',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
