# Generated by Django 5.0.7 on 2025-05-12 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutomazioneDati', '0045_remove_regsegnanti_impianto_nickname'),
        ('PortaleCorrispettivi', '0013_valoripun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contatore',
            name='impianto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contatori', to='PortaleCorrispettivi.impianto'),
        ),
    ]
