# Generated by Django 5.0.7 on 2025-05-13 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AutomazioneDati', '0047_letturacontatore_ora_lettura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letturacontatore',
            name='ora_lettura',
        ),
    ]
