# Generated by Django 5.0.7 on 2025-05-28 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutomazioneDati', '0050_alter_letturacontatore_tipo_tabella'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='letturacontatore',
            unique_together={('contatore', 'mese', 'anno')},
        ),
        migrations.AddField(
            model_name='letturacontatore',
            name='tipologiafascio',
            field=models.CharField(blank=True, choices=[('Monofascio', 'Monofascio'), ('Trifascio', 'Trifascio')], max_length=20, null=True, verbose_name='Tipologia Fascio'),
        ),
        migrations.RemoveField(
            model_name='letturacontatore',
            name='tipo_tabella',
        ),
    ]
