# Generated by Django 5.0.7 on 2025-05-28 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AutomazioneDati', '0051_alter_letturacontatore_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='letturacontatore',
            unique_together={('contatore', 'anno', 'mese')},
        ),
    ]
