# Generated by Django 5.0.7 on 2025-05-30 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutomazioneDati', '0052_alter_letturacontatore_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='letturacontatore',
            name='tipologia',
            field=models.CharField(blank=True, choices=[('Produzione', 'Produzione'), ('Scambio', 'Scambio'), ('Ausiliare', 'Ausiliare')], max_length=20, null=True, verbose_name='Tipologia'),
        ),
    ]
