# Generated by Django 5.0.7 on 2025-06-03 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AutomazioneDati', '0053_letturacontatore_tipologia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letturacontatore',
            name='tipologia',
        ),
        migrations.RemoveField(
            model_name='letturacontatore',
            name='tipologiafascio',
        ),
    ]
