# Generated by Django 5.0.7 on 2025-06-03 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutomazioneDati', '0054_remove_letturacontatore_tipologia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='letturacontatore',
            name='tipologia',
            field=models.CharField(blank=True, choices=[('Produzione', 'Produzione'), ('Scambio', 'Scambio'), ('Ausiliare', 'Ausiliare')], max_length=20, null=True, verbose_name='Tipologia'),
        ),
    ]
