# Generated by Django 5.0.7 on 2025-06-03 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutomazioneDati', '0055_letturacontatore_tipologia'),
    ]

    operations = [
        migrations.AddField(
            model_name='letturacontatore',
            name='tipologiafascio',
            field=models.CharField(blank=True, choices=[('Monofascio', 'Monofascio'), ('Trifascio', 'Trifascio')], max_length=20, null=True, verbose_name='Tipologia Fascio'),
        ),
    ]
