# Generated by Django 5.2.2 on 2025-06-05 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AutomazioneDati', '0056_letturacontatore_tipologiafascio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contatore',
            name='marca',
        ),
    ]
