"""
Django settings for PortaleImpianti_project project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_simple_env_file(env_path: Path) -> None:
    if not env_path.exists():
        return

    for raw_line in env_path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        os.environ.setdefault(key, value)


_load_simple_env_file(BASE_DIR.parent / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-wmxuimq!1g_in$#(0e!5tl+x^&i(rl8g&gc2^g%73ldt#(t%xd'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # formatting numeri in italiano
    'django.contrib.humanize',

    # packages
    'rest_framework',
    "django_static_echarts",

    # APPS
    "MonitoraggioImpianti.apps.MonitoraggioimpiantiConfig",
    "AnalisiDatiImpianti.apps.AnalisidatiimpiantiConfig",
    "AutomazioneDati.apps.AutomazionedatiConfig",
    "PortaleCorrispettivi.apps.PortalecorrispettiviConfig",
    "PortaleZilioService"
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"

ROOT_URLCONF = 'PortaleImpianti_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'PortaleImpianti_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        'OPTIONS': {
            'timeout': 120,  # seconds to wait for the write lock before raising OperationalError
        },
    }
}

SESSION_COOKIE_NAME = "sessionid_portale_impianti"
# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'it'

TIME_ZONE = 'Europe/Rome'

USE_I18N = True

USE_TZ = True

LOGIN_REDIRECT_URL = "home"
LOGOUT_REDIRECT_URL = "home"

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configurazione opzionale per l'intervallo di controllo dei dati PUN
PUN_CHECK_INTERVAL = timedelta(hours=6)  # Controlla ogni 6 ore

ZILIO_FATTURATO_ORDINARIO_URL = os.getenv(
    "ZILIO_FATTURATO_ORDINARIO_URL",
    "http://127.0.0.1:1234/fatturato-ordinario-anno-corrente-per-impianto/",
)
ZILIO_FATTURATO_ORDINARIO_TIMEOUT = float(
    os.getenv("ZILIO_FATTURATO_ORDINARIO_TIMEOUT", "3")
)
ZILIO_FATTURATO_STRAORDINARIO_URL = os.getenv(
    "ZILIO_FATTURATO_STRAORDINARIO_URL",
    "http://127.0.0.1:1234/fatturato-totale-straordinario-per-impianto/",
)
ZILIO_FATTURATO_STRAORDINARIO_TIMEOUT = float(
    os.getenv("ZILIO_FATTURATO_STRAORDINARIO_TIMEOUT", "3")
)
ZILIO_FATTURE_STRAORDINARIE_ANNUO_URL = os.getenv(
    "ZILIO_FATTURE_STRAORDINARIE_ANNUO_URL",
    "http://127.0.0.1:1234/numero-fatture-straordinarie-anno-corrente-per-impianto/",
)
ZILIO_FATTURE_STRAORDINARIE_ANNUO_TIMEOUT = float(
    os.getenv("ZILIO_FATTURE_STRAORDINARIE_ANNUO_TIMEOUT", "3")
)
ZILIO_FATTURE_STRAORDINARIE_TOTALI_URL = os.getenv(
    "ZILIO_FATTURE_STRAORDINARIE_TOTALI_URL",
    "http://127.0.0.1:1234/numero-fatture-straordinarie-totali-per-impianto/",
)
ZILIO_FATTURE_STRAORDINARIE_TOTALI_TIMEOUT = float(
    os.getenv("ZILIO_FATTURE_STRAORDINARIE_TOTALI_TIMEOUT", "3")
)
ZILIO_COSTO_STRAORDINARIO_TOTALE_URL = os.getenv(
    "ZILIO_COSTO_STRAORDINARIO_TOTALE_URL",
    "http://192.168.10.229:1546/costi-sostenuti-straordinari-da-inizio-contratto-per-impianto/",
)
ZILIO_COSTO_STRAORDINARIO_TOTALE_TIMEOUT = float(
    os.getenv("ZILIO_COSTO_STRAORDINARIO_TOTALE_TIMEOUT", "3")
)
ZILIO_CANONI_INCASSATI_OEM_URL = os.getenv(
    "ZILIO_CANONI_INCASSATI_OEM_URL",
    "http://192.168.10.229:1546/canoni-incassati-e-non-incassati-per-impianti-fv-oem/",
)
ZILIO_CANONI_INCASSATI_OEM_TIMEOUT = float(
    os.getenv("ZILIO_CANONI_INCASSATI_OEM_TIMEOUT", "3")
)
