# Generated by Django 5.1 on 2024-08-16 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortaleCorrispettivi', '0002_commento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commento',
            options={'verbose_name': 'Commento', 'verbose_name_plural': 'Commenti'},
        ),
        migrations.CreateModel(
            name='DiarioLetture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anno', models.IntegerField(help_text='Anno di lettura', verbose_name='Anno')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome file')),
                ('impianto', models.ForeignKey(help_text='Relativo Impianto', on_delete=django.db.models.deletion.CASCADE, to='PortaleCorrispettivi.impianto', verbose_name='Impianto')),
            ],
            options={
                'verbose_name': 'Diario letture',
                'verbose_name_plural': 'Diari lettura',
            },
        ),
    ]
