# Generated by Django 5.1 on 2024-08-16 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortaleCorrispettivi', '0003_alter_commento_options_diarioletture'),
    ]

    operations = [
        migrations.AddField(
            model_name='diarioletture',
            name='cartella',
            field=models.CharField(default='-', max_length=150, verbose_name='Cartella - Percorso'),
        ),
    ]
