# Generated by Django 5.1 on 2024-08-19 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortaleCorrispettivi', '0005_cashflow_datimensili'),
    ]

    operations = [
        migrations.AddField(
            model_name='diarioletture',
            name='unit',
            field=models.CharField(default='Z:/', max_length=150, verbose_name='Unità - Periferica'),
        ),
    ]
