# Generated by Django 5.1 on 2024-08-19 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortaleCorrispettivi', '0007_cashflow_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='datimensili',
            name='unit',
            field=models.CharField(default='Z:/', max_length=150, verbose_name='Unità - Periferica'),
        ),
    ]
