# Generated by Django 5.0.7 on 2025-05-09 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortaleCorrispettivi', '0009_linkportale'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatiMensiliTabella',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anno', models.IntegerField()),
                ('mese', models.IntegerField()),
                ('energia_kwh', models.FloatField(blank=True, null=True)),
                ('corrispettivo_incentivo', models.FloatField(blank=True, null=True)),
                ('corrispettivo_altro', models.FloatField(blank=True, null=True)),
                ('fatturazione_tfo', models.FloatField(blank=True, null=True)),
                ('fatturazione_altro', models.FloatField(blank=True, null=True)),
                ('incassi', models.FloatField(blank=True, null=True)),
                ('controllo_scarto', models.FloatField(blank=True, editable=False, null=True)),
                ('controllo_percentuale', models.FloatField(blank=True, editable=False, null=True)),
                ('impianto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PortaleCorrispettivi.impianto')),
            ],
            options={
                'verbose_name': 'Dato Mensile Tabella',
                'verbose_name_plural': 'Dati Mensili Tabella',
                'unique_together': {('impianto', 'anno', 'mese')},
            },
        ),
    ]
