# Generated by Django 5.0.7 on 2025-05-09 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PortaleCorrispettivi', '0011_datimensilitabella_origine_dati_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datimensilitabella',
            name='origine_dati',
        ),
    ]
