# Generated by Django 5.0.7 on 2025-05-12 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortaleCorrispettivi', '0012_remove_datimensilitabella_origine_dati'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValoriPUN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anno', models.IntegerField()),
                ('mese', models.IntegerField()),
                ('valore_medio', models.FloatField()),
            ],
            options={
                'verbose_name': 'Valore PUN',
                'verbose_name_plural': 'Valori PUN',
                'unique_together': {('anno', 'mese')},
            },
        ),
    ]
