# Generated by Django 5.0.7 on 2025-05-15 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PortaleCorrispettivi', '0013_valoripun'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ValoriPUN',
        ),
    ]
