# Generated by Django 5.0.7 on 2025-05-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortaleCorrispettivi', '0014_delete_valoripun'),
    ]

    operations = [
        migrations.AddField(
            model_name='datimensilitabella',
            name='media_pun_mensile',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
