# Generated by Django 5.0.7 on 2025-05-15 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortaleCorrispettivi', '0016_remove_datimensilitabella_media_pun_mensile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PunMonthlyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anno', models.IntegerField()),
                ('mese', models.IntegerField()),
                ('valore_medio', models.FloatField()),
                ('ultima_modifica', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('anno', 'mese')},
            },
        ),
    ]
