# Generated by Django 5.0.7 on 2025-05-15 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PortaleCorrispettivi', '0018_cashflow_anno_cashflow_tipo_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashflow',
            name='anno',
        ),
        migrations.RemoveField(
            model_name='cashflow',
            name='tipo_file',
        ),
    ]
