# Generated by Django 5.0.7 on 2025-09-08 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PortaleCorrispettivi", "0019_remove_cashflow_anno_remove_cashflow_tipo_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="DatiEnergiaNonIncentivata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anno", models.IntegerField()),
                ("mese", models.IntegerField()),
                ("DBGruppo", models.CharField(max_length=10)),
                ("ImportoUdc", models.FloatField()),
            ],
            options={
                "verbose_name": "Dati Energia Non Incentivata",
                "verbose_name_plural": "Dati Energia Non Incentivata",
                "unique_together": {("anno", "mese", "DBGruppo")},
            },
        ),
        migrations.CreateModel(
            name="DatiTFO",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anno", models.IntegerField()),
                ("mese", models.IntegerField()),
                ("DBGruppo", models.CharField(max_length=10)),
                ("ImportoUdc", models.FloatField()),
            ],
            options={
                "verbose_name": "Dati TFO",
                "verbose_name_plural": "Dati TFO",
                "unique_together": {("anno", "mese", "DBGruppo")},
            },
        ),
    ]
