# Generated by Django 5.0.7 on 2025-09-24 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "PortaleCorrispettivi",
            "0021_datienergianonincentivata_periodocompetenza_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="PunMonthlyData",
        ),
    ]
