# Generated by Django 5.0.7 on 2025-10-01 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PortaleCorrispettivi", "0022_delete_punmonthlydata"),
    ]

    operations = [
        migrations.CreateModel(
            name="commento_tabellacorrispettivi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anno", models.IntegerField(editable=False)),
                ("mese", models.IntegerField()),
                ("testo", models.TextField()),
                (
                    "stato",
                    models.CharField(
                        choices=[
                            ("empty", "Nessuno"),
                            ("ok", "Risolto"),
                            ("standby", "In lavorazione"),
                            ("alarm", "Problema"),
                        ],
                        default="",
                        max_length=50,
                    ),
                ),
                (
                    "impianto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PortaleCorrispettivi.impianto",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="DatiEnergiaNonIncentivata",
        ),
        migrations.DeleteModel(
            name="DatiTFO",
        ),
    ]
